# FAIL: Incorrect Policy Versions
truist.compositeauthn.policy.version: "1.0.0"
truist.authz.policy.version: "2.5.0"
noname.policy.version: "4.0.0"
ratelimit.policy.version: "1.0.0"
headerinjection.policy.version: "1.0.0"
headerremoval.policy.version: "1.0.0"
truist.wssencdec.policy.version: "2.0.0"
truist.jsonencdec.policy.version: "1.5.0"
truist.mTLS-AuthZ.policy.version: "1.0.0" # Fails if proxy check passes

# FAIL: Incorrect Property Values
headerinjection.policy.inboundheadermap.x-tfc-request-out: "INFO" # Should be WARN
headerinjection.policy.inboundheadermap.x-tfc-response-in: "ERROR" # Should be WARN
